### ISSUE TITLE
SharedPreferencesELinux error

### ISSUE THREAD

**Issue by JGNS** [sony/flutter-elinux-plugins#89]
hello，When I directly run main.dart, I receive the following error：
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: The "HOME" environment variable is not set. This package (and POSIX) requires that HOME be set.
Dec 04 15:19:16 ztl demo_nolibs[44332]: #0      _getDirectory (package:xdg_directories/xdg_directories.dart:120)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #1      _directoryFromEnvironmentWithFallback (package:xdg_directories/xdg_directories.dart:109)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #2      dataHome (package:xdg_directories/xdg_directories.dart:170)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #3      PathProviderELinux.getApplicationSupportPath (package:path_provider_elinux/src/path_provider_elinux.dart:52)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #4      SharedPreferencesELinux._getLocalDataFile (package:shared_preferences_elinux/shared_preferences_elinux.dart:46)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #5      SharedPreferencesELinux._reload (package:shared_preferences_elinux/shared_preferences_elinux.dart:56)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #6      SharedPreferencesELinux._readPreferences (package:shared_preferences_elinux/shared_preferences_elinux.dart:73)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #7      SharedPreferencesELinux.setValue (package:shared_preferences_elinux/shared_preferences_elinux.dart:157)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #8      SharedPreferencesELinuxExtention.set (package:demo_nolibs/utils/sp_util.dart:5)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #9      SPUtil.set (package:demo_nolibs/utils/sp_util.dart:14)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #10     _MyHomePageState.setCount (package:demo_nolibs/main.dart:70)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #11     _MyHomePageState.build.<anonymous closure> (package:demo_nolibs/main.dart:115)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #12     _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1154)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #13     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #14     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:654)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #15     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:311)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #16     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:244)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #17     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:630)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #18     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #19     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #20     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #21     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #22     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #23     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #24     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #25     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #26     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #27     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #28     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #29     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #30     _invoke1 (dart:ui/hooks.dart:186)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #31     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:424)
Dec 04 15:19:16 ztl demo_nolibs[44332]: #32     _dispatchPointerDataPacket (dart:ui/hooks.dart:119)
My dependencies ：
dependencies:
  flutter:
    sdk: flutter
  shared_preferences_elinux:
    git:
      url: https://github.com/sony/flutter-elinux-plugins.git
      path: packages/shared_preferences
      ref: main

env：
flutter-elinux --version
Flutter 3.13.9 • channel [user-branch] • unknown source
Framework • revision d211f42860 (6 周前) • 2023-10-25 13:42:25 -0700
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0

thanks~

**Comment by JGNS** [comment]
If I run the original counter program alone, no errors occur.

**Comment by HidenoriMatsubayashi** [comment]
> What is the HOME variable? There's no place to specify setting HOME. What is its value?

It's one of common system environments in Linux OS... You can search it in the internet.

Closing. Thanks.

**Comment by JGNS** [comment]
> > What is the HOME variable? There's no place to specify setting HOME. What is its value?
> 
> It's one of common system environments in Linux OS... You can search it in the internet.
> 
> Closing. Thanks.

I know about home, but what’s strange to me is this error message. Doesn’t my Linux have home? What should I do to make the program run properly. thanks.
